databases_namespace: com.liveramp.kafka_service.db_models
databases:
  -
    root_namespace: com.liveramp.kafka_service.db_models.db
    db_name: KafkaService
    schema_rb: schema.rb
    models: ../app/models
