
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.kafka_service.db_models.db.impl;

import java.io.IOException;
import java.sql.Connection;

import com.liveramp.kafka_service.db_models.db.IKafkaService;
import com.rapleaf.jack.BaseDatabaseConnection;
import com.liveramp.kafka_service.db_models.db.iface.IJobStatPersistence;

import com.liveramp.kafka_service.db_models.IDatabases;

public class KafkaServiceImpl implements IKafkaService {
  
  private final BaseDatabaseConnection conn;
  private final IJobStatPersistence job_stats;

  public KafkaServiceImpl(BaseDatabaseConnection conn, IDatabases databases) {
    this.conn = conn;
    this.job_stats = new BaseJobStatPersistenceImpl(conn, databases);
  }

  public IJobStatPersistence jobStats(){
    return job_stats;
  }

  public boolean deleteAll() throws IOException {
    boolean success = true;
    try {
    success &= job_stats.deleteAll();
    } catch (IOException e) {
      throw e;
    }
    return success;
  }

  public void disableCaching() {
    job_stats.disableCaching();
  }

  public void setAutoCommit(boolean autoCommit) {
    conn.setAutoCommit(autoCommit);
  }

  public boolean getAutoCommit() {
    return conn.getAutoCommit();
  }

  public void commit() {
    conn.commit();
  }

  public void rollback() {
    conn.rollback();
  }

  public void resetConnection() {
    conn.resetConnection();
  }

}
