
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.kafka_service.db_models.db.models;

import java.io.IOException;
import java.util.Collections;
import java.util.EnumSet;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.ModelWithId;
import com.rapleaf.jack.AttributesWithId;
import com.rapleaf.jack.BelongsToAssociation;
import com.rapleaf.jack.HasManyAssociation;
import com.rapleaf.jack.HasOneAssociation;
import com.rapleaf.jack.ModelIdWrapper;
import com.rapleaf.jack.queries.AbstractTable;
import com.rapleaf.jack.queries.Column;

import com.liveramp.kafka_service.db_models.IDatabases;

public class JobStat extends ModelWithId<JobStat, IDatabases> implements Comparable<JobStat>{
  
  public static final long serialVersionUID = -6346257958710742017L;

  public static class Tbl extends AbstractTable {
    public final Column ID;
    public final Column JOB_ID;
    public final Column COUNT_SUCCESS;
    public final Column COUNT_FAILURE;
    public final Column CREATED_AT;
    public final Column UPDATED_AT;
    public final Column COUNT_TOTAL;

    private Tbl(String alias) {
      super("job_stats", alias);
      this.ID = Column.fromId(alias);
      this.JOB_ID = Column.fromField(alias, _Fields.job_id, Long.class);
      this.COUNT_SUCCESS = Column.fromField(alias, _Fields.count_success, Long.class);
      this.COUNT_FAILURE = Column.fromField(alias, _Fields.count_failure, Long.class);
      this.CREATED_AT = Column.fromField(alias, _Fields.created_at, Long.class);
      this.UPDATED_AT = Column.fromField(alias, _Fields.updated_at, Long.class);
      this.COUNT_TOTAL = Column.fromField(alias, _Fields.count_total, Long.class);
      Collections.addAll(this.allColumns, ID, JOB_ID, COUNT_SUCCESS, COUNT_FAILURE, CREATED_AT, UPDATED_AT, COUNT_TOTAL);
    }

    public static Tbl as(String alias) {
      return new Tbl(alias);
    }
  }

  public static final Tbl TBL = new Tbl("job_stats");
  public static final Column ID = TBL.ID;
  public static final Column JOB_ID = TBL.JOB_ID;
  public static final Column COUNT_SUCCESS = TBL.COUNT_SUCCESS;
  public static final Column COUNT_FAILURE = TBL.COUNT_FAILURE;
  public static final Column CREATED_AT = TBL.CREATED_AT;
  public static final Column UPDATED_AT = TBL.UPDATED_AT;
  public static final Column COUNT_TOTAL = TBL.COUNT_TOTAL;

  private final Attributes attributes;

  private transient JobStat.Id cachedTypedId;

  // Associations

  public enum _Fields {
    job_id,
    count_success,
    count_failure,
    created_at,
    updated_at,
    count_total,
  }

  @Override
  public JobStat.Id getTypedId() {
    if (cachedTypedId == null) {
      cachedTypedId = new JobStat.Id(this.getId());
    }
    return cachedTypedId;
  }

  public JobStat(long id, final long job_id, final long count_success, final long count_failure, final long created_at, final long updated_at, final long count_total, IDatabases databases) {
    super(databases);
    attributes = new Attributes(id, job_id, count_success, count_failure, created_at, updated_at, count_total);
  }

  public JobStat(long id, final long job_id, final long count_success, final long count_failure, final long created_at, final long updated_at, final long count_total) {
    super(null);
    attributes = new Attributes(id, job_id, count_success, count_failure, created_at, updated_at, count_total);
  }
  
  public JobStat(long id, final long job_id, final long count_success, final long count_failure, final long updated_at, final long count_total, IDatabases databases) {
    super(databases);
    attributes = new Attributes(id, job_id, count_success, count_failure, updated_at, count_total);
  }

  public JobStat(long id, final long job_id, final long count_success, final long count_failure, final long updated_at, final long count_total) {
    super(null);
    attributes = new Attributes(id, job_id, count_success, count_failure, updated_at, count_total);
  }

  public static JobStat newDefaultInstance(long id) {
    return new JobStat(id, 0L, 0L, 0L, 0L, 0L, 0L);
  }

  public JobStat(Attributes attributes, IDatabases databases) {
    super(databases);
    this.attributes = attributes;
  }

  public JobStat(Attributes attributes) {
    super(null);
    this.attributes = attributes;
  }

  public JobStat(long id, Map<Enum, Object> fieldsMap) {
    super(null);
    attributes = new Attributes(id, fieldsMap);
  }

  public JobStat (JobStat other) {
    this(other, (IDatabases)null);
  }

  public JobStat (JobStat other, IDatabases databases) {
    super(databases);
    attributes = new Attributes(other.getAttributes());

    if (databases != null) {
    }
  }
  
  public Attributes getAttributes() {
    return attributes;
  }

  public long getJobId(){
    return attributes.getJobId();
  }

  public JobStat setJobId(long newval){
    attributes.setJobId(newval);
    cachedHashCode = 0;
    return this;
  }

  public long getCountSuccess(){
    return attributes.getCountSuccess();
  }

  public JobStat setCountSuccess(long newval){
    attributes.setCountSuccess(newval);
    cachedHashCode = 0;
    return this;
  }

  public long getCountFailure(){
    return attributes.getCountFailure();
  }

  public JobStat setCountFailure(long newval){
    attributes.setCountFailure(newval);
    cachedHashCode = 0;
    return this;
  }

  public long getCreatedAt(){
    return attributes.getCreatedAt();
  }

  public JobStat setCreatedAt(long newval){
    attributes.setCreatedAt(newval);
    cachedHashCode = 0;
    return this;
  }

  public long getUpdatedAt(){
    return attributes.getUpdatedAt();
  }

  public JobStat setUpdatedAt(long newval){
    attributes.setUpdatedAt(newval);
    cachedHashCode = 0;
    return this;
  }

  public long getCountTotal(){
    return attributes.getCountTotal();
  }

  public JobStat setCountTotal(long newval){
    attributes.setCountTotal(newval);
    cachedHashCode = 0;
    return this;
  }

  public void setField(_Fields field, Object value) {
    switch (field) {
      case job_id:
        setJobId((Long) value);
        break;
      case count_success:
        setCountSuccess((Long) value);
        break;
      case count_failure:
        setCountFailure((Long) value);
        break;
      case created_at:
        setCreatedAt((Long) value);
        break;
      case updated_at:
        setUpdatedAt((Long) value);
        break;
      case count_total:
        setCountTotal((Long) value);
        break;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }
  }
  
  public void setField(String fieldName, Object value) {
    if (fieldName.equals("job_id")) {
      setJobId((Long)  value);
      return;
    }
    if (fieldName.equals("count_success")) {
      setCountSuccess((Long)  value);
      return;
    }
    if (fieldName.equals("count_failure")) {
      setCountFailure((Long)  value);
      return;
    }
    if (fieldName.equals("created_at")) {
      setCreatedAt((Long)  value);
      return;
    }
    if (fieldName.equals("updated_at")) {
      setUpdatedAt((Long)  value);
      return;
    }
    if (fieldName.equals("count_total")) {
      setCountTotal((Long)  value);
      return;
    }
    throw new IllegalStateException("Invalid field: " + fieldName);
  }

  public static Class getFieldType(_Fields field) {
    switch (field) {
      case job_id:
        return long.class;
      case count_success:
        return long.class;
      case count_failure:
        return long.class;
      case created_at:
        return long.class;
      case updated_at:
        return long.class;
      case count_total:
        return long.class;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(String fieldName) {    
    if (fieldName.equals("job_id")) {
      return long.class;
    }
    if (fieldName.equals("count_success")) {
      return long.class;
    }
    if (fieldName.equals("count_failure")) {
      return long.class;
    }
    if (fieldName.equals("created_at")) {
      return long.class;
    }
    if (fieldName.equals("updated_at")) {
      return long.class;
    }
    if (fieldName.equals("count_total")) {
      return long.class;
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  @Override
  public Object getField(String fieldName) {
    if (fieldName.equals("id")) {
      return getId();
    }
    if (fieldName.equals("job_id")) {
      return getJobId();
    }
    if (fieldName.equals("count_success")) {
      return getCountSuccess();
    }
    if (fieldName.equals("count_failure")) {
      return getCountFailure();
    }
    if (fieldName.equals("created_at")) {
      return getCreatedAt();
    }
    if (fieldName.equals("updated_at")) {
      return getUpdatedAt();
    }
    if (fieldName.equals("count_total")) {
      return getCountTotal();
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  public Object getField(_Fields field) {
    switch (field) {
      case job_id:
        return getJobId();
      case count_success:
        return getCountSuccess();
      case count_failure:
        return getCountFailure();
      case created_at:
        return getCreatedAt();
      case updated_at:
        return getUpdatedAt();
      case count_total:
        return getCountTotal();
    }
    throw new IllegalStateException("Invalid field: " + field);
  }
  
  public boolean hasField(String fieldName) {
    if (fieldName.equals("id")) {
      return true;
    }
    if (fieldName.equals("job_id")) {
      return true;
    }
    if (fieldName.equals("count_success")) {
      return true;
    }
    if (fieldName.equals("count_failure")) {
      return true;
    }
    if (fieldName.equals("created_at")) {
      return true;
    }
    if (fieldName.equals("updated_at")) {
      return true;
    }
    if (fieldName.equals("count_total")) {
      return true;
    }
    return false;
  }

  public static Object getDefaultValue(_Fields field) {
    switch (field) {
      case job_id:
        return null;
      case count_success:
        return null;
      case count_failure:
        return null;
      case created_at:
        return null;
      case updated_at:
        return null;
      case count_total:
        return null;
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  @Override
  public Set<Enum> getFieldSet() {
    Set set = EnumSet.allOf(_Fields.class);
    return set;
  }

  @Override
  public JobStat getCopy() {
    return getCopy(databases);
  }

  @Override
  public JobStat getCopy(IDatabases databases) {
    return new JobStat(this, databases);
  }

  @Override
  public boolean save() throws IOException {
    return databases.getKafkaService().jobStats().save(this);
  }

  public String toString() {
    return "<JobStat"
      + " job_id: " + getJobId()
      + " count_success: " + getCountSuccess()
      + " count_failure: " + getCountFailure()
      + " created_at: " + getCreatedAt()
      + " updated_at: " + getUpdatedAt()
      + " count_total: " + getCountTotal()
      + ">";
  }

  public void unsetAssociations() {
    unsetDatabaseReference();
  }

  public int compareTo(JobStat that){
    return Long.valueOf(this.getId()).compareTo(that.getId());
  }
  
  
  public static class Attributes extends AttributesWithId {
    
    public static final long serialVersionUID = -6346257958710742017L;

    // Fields
    private long __job_id;
    private long __count_success;
    private long __count_failure;
    private long __created_at;
    private long __updated_at;
    private long __count_total;

    public Attributes(long id) {
      super(id);
    }

    public Attributes(long id, final long job_id, final long count_success, final long count_failure, final long created_at, final long updated_at, final long count_total) {
      super(id);
      this.__job_id = job_id;
      this.__count_success = count_success;
      this.__count_failure = count_failure;
      this.__created_at = created_at;
      this.__updated_at = updated_at;
      this.__count_total = count_total;
    }
    
    public Attributes(long id, final long job_id, final long count_success, final long count_failure, final long updated_at, final long count_total) {
      super(id);
      this.__job_id = job_id;
      this.__count_success = count_success;
      this.__count_failure = count_failure;
      this.__updated_at = updated_at;
      this.__count_total = count_total;
      this.__created_at = System.currentTimeMillis();
    }

    public static Attributes newDefaultInstance(long id) {
      return new Attributes(id, 0L, 0L, 0L, 0L, 0L, 0L);
    }

    public Attributes(long id, Map<Enum, Object> fieldsMap) {
      super(id);
      long job_id = (Long) fieldsMap.get(JobStat._Fields.job_id);
      long count_success = (Long) fieldsMap.get(JobStat._Fields.count_success);
      long count_failure = (Long) fieldsMap.get(JobStat._Fields.count_failure);
      long created_at = (Long) fieldsMap.get(JobStat._Fields.created_at);
      long updated_at = (Long) fieldsMap.get(JobStat._Fields.updated_at);
      long count_total = (Long) fieldsMap.get(JobStat._Fields.count_total);
      this.__job_id = job_id;
      this.__count_success = count_success;
      this.__count_failure = count_failure;
      this.__created_at = created_at;
      this.__updated_at = updated_at;
      this.__count_total = count_total;
    }

    public Attributes(Attributes other) {
      super(other.getId());
      this.__job_id = other.getJobId();
      this.__count_success = other.getCountSuccess();
      this.__count_failure = other.getCountFailure();
      this.__created_at = other.getCreatedAt();
      this.__updated_at = other.getUpdatedAt();
      this.__count_total = other.getCountTotal();
    }

    public long getJobId(){
      return __job_id;
    }

    public Attributes setJobId(long newval){
      this.__job_id = newval;
      cachedHashCode = 0;
      return this;
    }

    public long getCountSuccess(){
      return __count_success;
    }

    public Attributes setCountSuccess(long newval){
      this.__count_success = newval;
      cachedHashCode = 0;
      return this;
    }

    public long getCountFailure(){
      return __count_failure;
    }

    public Attributes setCountFailure(long newval){
      this.__count_failure = newval;
      cachedHashCode = 0;
      return this;
    }

    public long getCreatedAt(){
      return __created_at;
    }

    public Attributes setCreatedAt(long newval){
      this.__created_at = newval;
      cachedHashCode = 0;
      return this;
    }

    public long getUpdatedAt(){
      return __updated_at;
    }

    public Attributes setUpdatedAt(long newval){
      this.__updated_at = newval;
      cachedHashCode = 0;
      return this;
    }

    public long getCountTotal(){
      return __count_total;
    }

    public Attributes setCountTotal(long newval){
      this.__count_total = newval;
      cachedHashCode = 0;
      return this;
    }

    public void setField(_Fields field, Object value) {
      switch (field) {
        case job_id:
          setJobId((Long) value);
          break;
        case count_success:
          setCountSuccess((Long) value);
          break;
        case count_failure:
          setCountFailure((Long) value);
          break;
        case created_at:
          setCreatedAt((Long) value);
          break;
        case updated_at:
          setUpdatedAt((Long) value);
          break;
        case count_total:
          setCountTotal((Long) value);
          break;
        default:
          throw new IllegalStateException("Invalid field: " + field);
      }
    }

    public void setField(String fieldName, Object value) {
      if (fieldName.equals("job_id")) {
        setJobId((Long)  value);
        return;
      }
      if (fieldName.equals("count_success")) {
        setCountSuccess((Long)  value);
        return;
      }
      if (fieldName.equals("count_failure")) {
        setCountFailure((Long)  value);
        return;
      }
      if (fieldName.equals("created_at")) {
        setCreatedAt((Long)  value);
        return;
      }
      if (fieldName.equals("updated_at")) {
        setUpdatedAt((Long)  value);
        return;
      }
      if (fieldName.equals("count_total")) {
        setCountTotal((Long)  value);
        return;
      }
      throw new IllegalStateException("Invalid field: " + fieldName);
    }

    public static Class getFieldType(_Fields field) {
      switch (field) {
        case job_id:
          return long.class;
        case count_success:
          return long.class;
        case count_failure:
          return long.class;
        case created_at:
          return long.class;
        case updated_at:
          return long.class;
        case count_total:
          return long.class;
        default:
          throw new IllegalStateException("Invalid field: " + field);
      }    
    }

    public static Class getFieldType(String fieldName) {    
      if (fieldName.equals("job_id")) {
        return long.class;
      }
      if (fieldName.equals("count_success")) {
        return long.class;
      }
      if (fieldName.equals("count_failure")) {
        return long.class;
      }
      if (fieldName.equals("created_at")) {
        return long.class;
      }
      if (fieldName.equals("updated_at")) {
        return long.class;
      }
      if (fieldName.equals("count_total")) {
        return long.class;
      }
      throw new IllegalStateException("Invalid field name: " + fieldName);
    }

    @Override
    public Object getField(String fieldName) {
      if (fieldName.equals("id")) {
        return getId();
      }
      if (fieldName.equals("job_id")) {
        return getJobId();
      }
      if (fieldName.equals("count_success")) {
        return getCountSuccess();
      }
      if (fieldName.equals("count_failure")) {
        return getCountFailure();
      }
      if (fieldName.equals("created_at")) {
        return getCreatedAt();
      }
      if (fieldName.equals("updated_at")) {
        return getUpdatedAt();
      }
      if (fieldName.equals("count_total")) {
        return getCountTotal();
      }
      throw new IllegalStateException("Invalid field name: " + fieldName);
    }

    public Object getField(_Fields field) {
      switch (field) {
        case job_id:
          return getJobId();
        case count_success:
          return getCountSuccess();
        case count_failure:
          return getCountFailure();
        case created_at:
          return getCreatedAt();
        case updated_at:
          return getUpdatedAt();
        case count_total:
          return getCountTotal();
      }
      throw new IllegalStateException("Invalid field: " + field);
    }

    public boolean hasField(String fieldName) {
      if (fieldName.equals("id")) {
        return true;
      }
      if (fieldName.equals("job_id")) {
        return true;
      }
      if (fieldName.equals("count_success")) {
        return true;
      }
      if (fieldName.equals("count_failure")) {
        return true;
      }
      if (fieldName.equals("created_at")) {
        return true;
      }
      if (fieldName.equals("updated_at")) {
        return true;
      }
      if (fieldName.equals("count_total")) {
        return true;
      }
      return false;
    }

    public static Object getDefaultValue(_Fields field) {
      switch (field) {
        case job_id:
          return null;
        case count_success:
          return null;
        case count_failure:
          return null;
        case created_at:
          return null;
        case updated_at:
          return null;
        case count_total:
          return null;
      }
      throw new IllegalStateException("Invalid field: " + field);
    }
    
    @Override
    public Set<Enum> getFieldSet() {
      Set set = EnumSet.allOf(_Fields.class);
      return set;
    }
    
    public String toString() {
      return "<JobStat.Attributes"
        + " job_id: " + getJobId()
        + " count_success: " + getCountSuccess()
        + " count_failure: " + getCountFailure()
        + " created_at: " + getCreatedAt()
        + " updated_at: " + getUpdatedAt()
        + " count_total: " + getCountTotal()
        + ">";
    }
  }

  public static class Id implements ModelIdWrapper<JobStat.Id> {
    public static final long serialVersionUID = 1L;

    private final long id;

    public Id(Long id) {
      this.id = id;
    }

    @Override
    public Long getId() {
      return Long.valueOf(this.id);
    }

    @Override
    public int compareTo(Id other) {
      return this.getId().compareTo(other.getId());
    }

    @Override
    public boolean equals(Object other) {
      if (other instanceof Id) {
        return this.getId().equals(((Id) other).getId());
      }
      return false;
    }

    @Override
    public int hashCode() {
      return this.getId().hashCode();
    }

    @Override
    public String toString() {
      return "<JobStat.Id: "+this.getId()+">";
    }
  }

  public static Set<Attributes> convertToAttributesSet(Set<JobStat> models) {
    Set<Attributes> attributes = new HashSet<Attributes>();
    for (JobStat model : models) {
      attributes.add(model.getAttributes());
    }
    return attributes;
  }

}
