
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.kafka_service.db_models.db.models;

import java.io.IOException;
import java.util.Collections;
import java.util.EnumSet;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.ModelWithId;
import com.rapleaf.jack.AttributesWithId;
import com.rapleaf.jack.BelongsToAssociation;
import com.rapleaf.jack.HasManyAssociation;
import com.rapleaf.jack.HasOneAssociation;
import com.rapleaf.jack.ModelIdWrapper;
import com.rapleaf.jack.queries.AbstractTable;
import com.rapleaf.jack.queries.Column;

import com.liveramp.kafka_service.db_models.IDatabases;

public class JobStat extends ModelWithId<JobStat, IDatabases> implements Comparable<JobStat>{
  
  public static final long serialVersionUID = -8761628191546601725L;

  public static class Tbl extends AbstractTable {
    public final Column ID;
    public final Column JOB_ID;
    public final Column COUNT_ERROR;
    public final Column COUNT_ACTUAL_TOTAL;
    public final Column COUNT_EXPECTED_TOTAL;
    public final Column CREATED_AT;
    public final Column UPDATED_AT;

    private Tbl(String alias) {
      super("job_stats", alias);
      this.ID = Column.fromId(alias);
      this.JOB_ID = Column.fromField(alias, _Fields.job_id, Long.class);
      this.COUNT_ERROR = Column.fromField(alias, _Fields.count_error, Long.class);
      this.COUNT_ACTUAL_TOTAL = Column.fromField(alias, _Fields.count_actual_total, Long.class);
      this.COUNT_EXPECTED_TOTAL = Column.fromField(alias, _Fields.count_expected_total, Long.class);
      this.CREATED_AT = Column.fromField(alias, _Fields.created_at, Long.class);
      this.UPDATED_AT = Column.fromField(alias, _Fields.updated_at, Long.class);
      Collections.addAll(this.allColumns, ID, JOB_ID, COUNT_ERROR, COUNT_ACTUAL_TOTAL, COUNT_EXPECTED_TOTAL, CREATED_AT, UPDATED_AT);
    }

    public static Tbl as(String alias) {
      return new Tbl(alias);
    }
  }

  public static final Tbl TBL = new Tbl("job_stats");
  public static final Column ID = TBL.ID;
  public static final Column JOB_ID = TBL.JOB_ID;
  public static final Column COUNT_ERROR = TBL.COUNT_ERROR;
  public static final Column COUNT_ACTUAL_TOTAL = TBL.COUNT_ACTUAL_TOTAL;
  public static final Column COUNT_EXPECTED_TOTAL = TBL.COUNT_EXPECTED_TOTAL;
  public static final Column CREATED_AT = TBL.CREATED_AT;
  public static final Column UPDATED_AT = TBL.UPDATED_AT;

  private final Attributes attributes;

  private transient JobStat.Id cachedTypedId;

  // Associations

  public enum _Fields {
    job_id,
    count_error,
    count_actual_total,
    count_expected_total,
    created_at,
    updated_at,
  }

  @Override
  public JobStat.Id getTypedId() {
    if (cachedTypedId == null) {
      cachedTypedId = new JobStat.Id(this.getId());
    }
    return cachedTypedId;
  }

  public JobStat(long id, final long job_id, final Long count_error, final Long count_actual_total, final Long count_expected_total, final long created_at, final long updated_at, IDatabases databases) {
    super(databases);
    attributes = new Attributes(id, job_id, count_error, count_actual_total, count_expected_total, created_at, updated_at);
  }

  public JobStat(long id, final long job_id, final Long count_error, final Long count_actual_total, final Long count_expected_total, final long created_at, final long updated_at) {
    super(null);
    attributes = new Attributes(id, job_id, count_error, count_actual_total, count_expected_total, created_at, updated_at);
  }
  
  public JobStat(long id, final long job_id, final Long count_error, final Long count_actual_total, final Long count_expected_total, final long updated_at, IDatabases databases) {
    super(databases);
    attributes = new Attributes(id, job_id, count_error, count_actual_total, count_expected_total, updated_at);
  }

  public JobStat(long id, final long job_id, final Long count_error, final Long count_actual_total, final Long count_expected_total, final long updated_at) {
    super(null);
    attributes = new Attributes(id, job_id, count_error, count_actual_total, count_expected_total, updated_at);
  }
  
  public JobStat(long id, final long job_id, final long created_at, final long updated_at, IDatabases databases) {
    super(databases);
    attributes = new Attributes(id, job_id, created_at, updated_at);
  }

  public JobStat(long id, final long job_id, final long created_at, final long updated_at) {
    super(null);
    attributes = new Attributes(id, job_id, created_at, updated_at);
  }
   
  public JobStat(long id, final long job_id, final long updated_at, IDatabases databases) {
    super(databases);
    attributes = new Attributes(id, job_id, updated_at);
  }

  public JobStat(long id, final long job_id, final long updated_at) {
    super(null);
    attributes = new Attributes(id, job_id, updated_at);
  }

  public static JobStat newDefaultInstance(long id) {
    return new JobStat(id, 0L, 0L, 0L);
  }

  public JobStat(Attributes attributes, IDatabases databases) {
    super(databases);
    this.attributes = attributes;
  }

  public JobStat(Attributes attributes) {
    super(null);
    this.attributes = attributes;
  }

  public JobStat(long id, Map<Enum, Object> fieldsMap) {
    super(null);
    attributes = new Attributes(id, fieldsMap);
  }

  public JobStat (JobStat other) {
    this(other, (IDatabases)null);
  }

  public JobStat (JobStat other, IDatabases databases) {
    super(databases);
    attributes = new Attributes(other.getAttributes());

    if (databases != null) {
    }
  }
  
  public Attributes getAttributes() {
    return attributes;
  }

  public long getJobId(){
    return attributes.getJobId();
  }

  public JobStat setJobId(long newval){
    attributes.setJobId(newval);
    cachedHashCode = 0;
    return this;
  }

  public Long getCountError(){
    return attributes.getCountError();
  }

  public JobStat setCountError(Long newval){
    attributes.setCountError(newval);
    cachedHashCode = 0;
    return this;
  }

  public Long getCountActualTotal(){
    return attributes.getCountActualTotal();
  }

  public JobStat setCountActualTotal(Long newval){
    attributes.setCountActualTotal(newval);
    cachedHashCode = 0;
    return this;
  }

  public Long getCountExpectedTotal(){
    return attributes.getCountExpectedTotal();
  }

  public JobStat setCountExpectedTotal(Long newval){
    attributes.setCountExpectedTotal(newval);
    cachedHashCode = 0;
    return this;
  }

  public long getCreatedAt(){
    return attributes.getCreatedAt();
  }

  public JobStat setCreatedAt(long newval){
    attributes.setCreatedAt(newval);
    cachedHashCode = 0;
    return this;
  }

  public long getUpdatedAt(){
    return attributes.getUpdatedAt();
  }

  public JobStat setUpdatedAt(long newval){
    attributes.setUpdatedAt(newval);
    cachedHashCode = 0;
    return this;
  }

  public void setField(_Fields field, Object value) {
    switch (field) {
      case job_id:
        setJobId((Long) value);
        break;
      case count_error:
        setCountError((Long) value);
        break;
      case count_actual_total:
        setCountActualTotal((Long) value);
        break;
      case count_expected_total:
        setCountExpectedTotal((Long) value);
        break;
      case created_at:
        setCreatedAt((Long) value);
        break;
      case updated_at:
        setUpdatedAt((Long) value);
        break;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }
  }
  
  public void setField(String fieldName, Object value) {
    if (fieldName.equals("job_id")) {
      setJobId((Long)  value);
      return;
    }
    if (fieldName.equals("count_error")) {
      setCountError((Long)  value);
      return;
    }
    if (fieldName.equals("count_actual_total")) {
      setCountActualTotal((Long)  value);
      return;
    }
    if (fieldName.equals("count_expected_total")) {
      setCountExpectedTotal((Long)  value);
      return;
    }
    if (fieldName.equals("created_at")) {
      setCreatedAt((Long)  value);
      return;
    }
    if (fieldName.equals("updated_at")) {
      setUpdatedAt((Long)  value);
      return;
    }
    throw new IllegalStateException("Invalid field: " + fieldName);
  }

  public static Class getFieldType(_Fields field) {
    switch (field) {
      case job_id:
        return long.class;
      case count_error:
        return Long.class;
      case count_actual_total:
        return Long.class;
      case count_expected_total:
        return Long.class;
      case created_at:
        return long.class;
      case updated_at:
        return long.class;
      default:
        throw new IllegalStateException("Invalid field: " + field);
    }    
  }

  public static Class getFieldType(String fieldName) {    
    if (fieldName.equals("job_id")) {
      return long.class;
    }
    if (fieldName.equals("count_error")) {
      return Long.class;
    }
    if (fieldName.equals("count_actual_total")) {
      return Long.class;
    }
    if (fieldName.equals("count_expected_total")) {
      return Long.class;
    }
    if (fieldName.equals("created_at")) {
      return long.class;
    }
    if (fieldName.equals("updated_at")) {
      return long.class;
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  @Override
  public Object getField(String fieldName) {
    if (fieldName.equals("id")) {
      return getId();
    }
    if (fieldName.equals("job_id")) {
      return getJobId();
    }
    if (fieldName.equals("count_error")) {
      return getCountError();
    }
    if (fieldName.equals("count_actual_total")) {
      return getCountActualTotal();
    }
    if (fieldName.equals("count_expected_total")) {
      return getCountExpectedTotal();
    }
    if (fieldName.equals("created_at")) {
      return getCreatedAt();
    }
    if (fieldName.equals("updated_at")) {
      return getUpdatedAt();
    }
    throw new IllegalStateException("Invalid field name: " + fieldName);
  }

  public Object getField(_Fields field) {
    switch (field) {
      case job_id:
        return getJobId();
      case count_error:
        return getCountError();
      case count_actual_total:
        return getCountActualTotal();
      case count_expected_total:
        return getCountExpectedTotal();
      case created_at:
        return getCreatedAt();
      case updated_at:
        return getUpdatedAt();
    }
    throw new IllegalStateException("Invalid field: " + field);
  }
  
  public boolean hasField(String fieldName) {
    if (fieldName.equals("id")) {
      return true;
    }
    if (fieldName.equals("job_id")) {
      return true;
    }
    if (fieldName.equals("count_error")) {
      return true;
    }
    if (fieldName.equals("count_actual_total")) {
      return true;
    }
    if (fieldName.equals("count_expected_total")) {
      return true;
    }
    if (fieldName.equals("created_at")) {
      return true;
    }
    if (fieldName.equals("updated_at")) {
      return true;
    }
    return false;
  }

  public static Object getDefaultValue(_Fields field) {
    switch (field) {
      case job_id:
        return null;
      case count_error:
        return 0;
      case count_actual_total:
        return 0;
      case count_expected_total:
        return 0;
      case created_at:
        return null;
      case updated_at:
        return null;
    }
    throw new IllegalStateException("Invalid field: " + field);
  }

  @Override
  public Set<Enum> getFieldSet() {
    Set set = EnumSet.allOf(_Fields.class);
    return set;
  }

  @Override
  public JobStat getCopy() {
    return getCopy(databases);
  }

  @Override
  public JobStat getCopy(IDatabases databases) {
    return new JobStat(this, databases);
  }

  @Override
  public boolean save() throws IOException {
    return databases.getKafkaService().jobStats().save(this);
  }

  public String toString() {
    return "<JobStat"
      + " job_id: " + getJobId()
      + " count_error: " + getCountError()
      + " count_actual_total: " + getCountActualTotal()
      + " count_expected_total: " + getCountExpectedTotal()
      + " created_at: " + getCreatedAt()
      + " updated_at: " + getUpdatedAt()
      + ">";
  }

  public void unsetAssociations() {
    unsetDatabaseReference();
  }

  public int compareTo(JobStat that){
    return Long.valueOf(this.getId()).compareTo(that.getId());
  }
  
  
  public static class Attributes extends AttributesWithId {
    
    public static final long serialVersionUID = -8761628191546601725L;

    // Fields
    private long __job_id;
    private Long __count_error;
    private Long __count_actual_total;
    private Long __count_expected_total;
    private long __created_at;
    private long __updated_at;

    public Attributes(long id) {
      super(id);
    }

    public Attributes(long id, final long job_id, final Long count_error, final Long count_actual_total, final Long count_expected_total, final long created_at, final long updated_at) {
      super(id);
      this.__job_id = job_id;
      this.__count_error = count_error;
      this.__count_actual_total = count_actual_total;
      this.__count_expected_total = count_expected_total;
      this.__created_at = created_at;
      this.__updated_at = updated_at;
    }
    
    public Attributes(long id, final long job_id, final Long count_error, final Long count_actual_total, final Long count_expected_total, final long updated_at) {
      super(id);
      this.__job_id = job_id;
      this.__count_error = count_error;
      this.__count_actual_total = count_actual_total;
      this.__count_expected_total = count_expected_total;
      this.__updated_at = updated_at;
      this.__created_at = System.currentTimeMillis();
    }
    
    public Attributes(long id, final long job_id, final long created_at, final long updated_at) {
      super(id);
      this.__job_id = job_id;
      this.__created_at = created_at;
      this.__updated_at = updated_at;
    }
    
    public Attributes(long id, final long job_id, final long updated_at) {
      super(id);
      this.__job_id = job_id;
      this.__updated_at = updated_at;
      this.__created_at = System.currentTimeMillis();
    }

    public static Attributes newDefaultInstance(long id) {
      return new Attributes(id, 0L, 0L, 0L);
    }

    public Attributes(long id, Map<Enum, Object> fieldsMap) {
      super(id);
      long job_id = (Long) fieldsMap.get(JobStat._Fields.job_id);
      Long count_error_tmp = (Long) fieldsMap.get(JobStat._Fields.count_error);
      Long count_error = count_error_tmp == null ? 0 : count_error_tmp;
      Long count_actual_total_tmp = (Long) fieldsMap.get(JobStat._Fields.count_actual_total);
      Long count_actual_total = count_actual_total_tmp == null ? 0 : count_actual_total_tmp;
      Long count_expected_total_tmp = (Long) fieldsMap.get(JobStat._Fields.count_expected_total);
      Long count_expected_total = count_expected_total_tmp == null ? 0 : count_expected_total_tmp;
      long created_at = (Long) fieldsMap.get(JobStat._Fields.created_at);
      long updated_at = (Long) fieldsMap.get(JobStat._Fields.updated_at);
      this.__job_id = job_id;
      this.__count_error = count_error;
      this.__count_actual_total = count_actual_total;
      this.__count_expected_total = count_expected_total;
      this.__created_at = created_at;
      this.__updated_at = updated_at;
    }

    public Attributes(Attributes other) {
      super(other.getId());
      this.__job_id = other.getJobId();
      this.__count_error = other.getCountError();
      this.__count_actual_total = other.getCountActualTotal();
      this.__count_expected_total = other.getCountExpectedTotal();
      this.__created_at = other.getCreatedAt();
      this.__updated_at = other.getUpdatedAt();
    }

    public long getJobId(){
      return __job_id;
    }

    public Attributes setJobId(long newval){
      this.__job_id = newval;
      cachedHashCode = 0;
      return this;
    }

    public Long getCountError(){
      return __count_error;
    }

    public Attributes setCountError(Long newval){
      this.__count_error = newval;
      cachedHashCode = 0;
      return this;
    }

    public Long getCountActualTotal(){
      return __count_actual_total;
    }

    public Attributes setCountActualTotal(Long newval){
      this.__count_actual_total = newval;
      cachedHashCode = 0;
      return this;
    }

    public Long getCountExpectedTotal(){
      return __count_expected_total;
    }

    public Attributes setCountExpectedTotal(Long newval){
      this.__count_expected_total = newval;
      cachedHashCode = 0;
      return this;
    }

    public long getCreatedAt(){
      return __created_at;
    }

    public Attributes setCreatedAt(long newval){
      this.__created_at = newval;
      cachedHashCode = 0;
      return this;
    }

    public long getUpdatedAt(){
      return __updated_at;
    }

    public Attributes setUpdatedAt(long newval){
      this.__updated_at = newval;
      cachedHashCode = 0;
      return this;
    }

    public void setField(_Fields field, Object value) {
      switch (field) {
        case job_id:
          setJobId((Long) value);
          break;
        case count_error:
          setCountError((Long) value);
          break;
        case count_actual_total:
          setCountActualTotal((Long) value);
          break;
        case count_expected_total:
          setCountExpectedTotal((Long) value);
          break;
        case created_at:
          setCreatedAt((Long) value);
          break;
        case updated_at:
          setUpdatedAt((Long) value);
          break;
        default:
          throw new IllegalStateException("Invalid field: " + field);
      }
    }

    public void setField(String fieldName, Object value) {
      if (fieldName.equals("job_id")) {
        setJobId((Long)  value);
        return;
      }
      if (fieldName.equals("count_error")) {
        setCountError((Long)  value);
        return;
      }
      if (fieldName.equals("count_actual_total")) {
        setCountActualTotal((Long)  value);
        return;
      }
      if (fieldName.equals("count_expected_total")) {
        setCountExpectedTotal((Long)  value);
        return;
      }
      if (fieldName.equals("created_at")) {
        setCreatedAt((Long)  value);
        return;
      }
      if (fieldName.equals("updated_at")) {
        setUpdatedAt((Long)  value);
        return;
      }
      throw new IllegalStateException("Invalid field: " + fieldName);
    }

    public static Class getFieldType(_Fields field) {
      switch (field) {
        case job_id:
          return long.class;
        case count_error:
          return Long.class;
        case count_actual_total:
          return Long.class;
        case count_expected_total:
          return Long.class;
        case created_at:
          return long.class;
        case updated_at:
          return long.class;
        default:
          throw new IllegalStateException("Invalid field: " + field);
      }    
    }

    public static Class getFieldType(String fieldName) {    
      if (fieldName.equals("job_id")) {
        return long.class;
      }
      if (fieldName.equals("count_error")) {
        return Long.class;
      }
      if (fieldName.equals("count_actual_total")) {
        return Long.class;
      }
      if (fieldName.equals("count_expected_total")) {
        return Long.class;
      }
      if (fieldName.equals("created_at")) {
        return long.class;
      }
      if (fieldName.equals("updated_at")) {
        return long.class;
      }
      throw new IllegalStateException("Invalid field name: " + fieldName);
    }

    @Override
    public Object getField(String fieldName) {
      if (fieldName.equals("id")) {
        return getId();
      }
      if (fieldName.equals("job_id")) {
        return getJobId();
      }
      if (fieldName.equals("count_error")) {
        return getCountError();
      }
      if (fieldName.equals("count_actual_total")) {
        return getCountActualTotal();
      }
      if (fieldName.equals("count_expected_total")) {
        return getCountExpectedTotal();
      }
      if (fieldName.equals("created_at")) {
        return getCreatedAt();
      }
      if (fieldName.equals("updated_at")) {
        return getUpdatedAt();
      }
      throw new IllegalStateException("Invalid field name: " + fieldName);
    }

    public Object getField(_Fields field) {
      switch (field) {
        case job_id:
          return getJobId();
        case count_error:
          return getCountError();
        case count_actual_total:
          return getCountActualTotal();
        case count_expected_total:
          return getCountExpectedTotal();
        case created_at:
          return getCreatedAt();
        case updated_at:
          return getUpdatedAt();
      }
      throw new IllegalStateException("Invalid field: " + field);
    }

    public boolean hasField(String fieldName) {
      if (fieldName.equals("id")) {
        return true;
      }
      if (fieldName.equals("job_id")) {
        return true;
      }
      if (fieldName.equals("count_error")) {
        return true;
      }
      if (fieldName.equals("count_actual_total")) {
        return true;
      }
      if (fieldName.equals("count_expected_total")) {
        return true;
      }
      if (fieldName.equals("created_at")) {
        return true;
      }
      if (fieldName.equals("updated_at")) {
        return true;
      }
      return false;
    }

    public static Object getDefaultValue(_Fields field) {
      switch (field) {
        case job_id:
          return null;
        case count_error:
          return 0;
        case count_actual_total:
          return 0;
        case count_expected_total:
          return 0;
        case created_at:
          return null;
        case updated_at:
          return null;
      }
      throw new IllegalStateException("Invalid field: " + field);
    }
    
    @Override
    public Set<Enum> getFieldSet() {
      Set set = EnumSet.allOf(_Fields.class);
      return set;
    }
    
    public String toString() {
      return "<JobStat.Attributes"
        + " job_id: " + getJobId()
        + " count_error: " + getCountError()
        + " count_actual_total: " + getCountActualTotal()
        + " count_expected_total: " + getCountExpectedTotal()
        + " created_at: " + getCreatedAt()
        + " updated_at: " + getUpdatedAt()
        + ">";
    }
  }

  public static class Id implements ModelIdWrapper<JobStat.Id> {
    public static final long serialVersionUID = 1L;

    private final long id;

    public Id(Long id) {
      this.id = id;
    }

    @Override
    public Long getId() {
      return Long.valueOf(this.id);
    }

    @Override
    public int compareTo(Id other) {
      return this.getId().compareTo(other.getId());
    }

    @Override
    public boolean equals(Object other) {
      if (other instanceof Id) {
        return this.getId().equals(((Id) other).getId());
      }
      return false;
    }

    @Override
    public int hashCode() {
      return this.getId().hashCode();
    }

    @Override
    public String toString() {
      return "<JobStat.Id: "+this.getId()+">";
    }
  }

  public static Set<Attributes> convertToAttributesSet(Set<JobStat> models) {
    Set<Attributes> attributes = new HashSet<Attributes>();
    for (JobStat model : models) {
      attributes.add(model.getAttributes());
    }
    return attributes;
  }

}
