
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.kafka_service.db_models.db;

import java.io.IOException;
import java.sql.SQLException;

import com.rapleaf.jack.DbFixtures;
import com.liveramp.kafka_service.db_models.DatabasesImpl;
import com.liveramp.kafka_service.db_models.IDatabases;

public class BaseDatabaseFixtures extends DbFixtures {

  public static void setup() throws SQLException, IOException {
    setup(new DatabasesImpl());
  }

  public static void setup(IDatabases databases) throws SQLException, IOException {
    databases.getKafkaService().jobStats().deleteAll();
  }
}
