
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.kafka_service.db_models.db;

import com.rapleaf.jack.IDb;
import com.liveramp.kafka_service.db_models.db.iface.IJobStatPersistence;

public interface IDatabase extends IDb {
  public IJobStatPersistence jobStats();
}
