
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.liveramp.kafka_service.db_models;
import com.liveramp.kafka_service.db_models.db.IKafkaService;

import com.rapleaf.jack.GenericDatabases;

public interface IDatabases extends GenericDatabases {
  public IKafkaService getKafkaService();
}
